### ISSUE TITLE
Library scan failing

### ISSUE THREAD

**Issue by Hutch79** [fredrikburmester/streamystats#15]
Heya,
I just installed Streamystats and started the first Full Sync.
After it reported it's finished, I looked at the stats and noticed that no watch stats were there and also the episode count in the library stats was not correct.
I've got around 40k episodes, but it only shows me 28.6k.

Here is the Log I found, I hope I got all the relevant parts.
If you need anything else, just hit me up!

```
phoenix-1  | 11:20:09.994 request_id=GDMZlVs7IhoUvd4AACjB [info] Sent 200 in 699µs
app-1      | 2058 |     throw @makeErrorWithCode(67, "Socket already assigned");
app-1      |                                    ^
app-1      | error: Socket already assigned
app-1      |  code: "ERR_HTTP_SOCKET_ASSIGNED"
app-1      | 
app-1      |       at assignSocketInternal (node:http:2058:29)
app-1      |       at onNodeHTTPRequest (node:http:554:33)
app-1      | 
app-1      | 2053 |   if (self[kCloseCallback])
app-1      | 2054 |     throw new Error("Close callback already set");
app-1      | 2055 |   self[kCloseCallback] = callback;
app-1      | 2056 | }
app-1      | 2057 | function assignSocketInternal(self, socket) {
app-1      | 2058 |     throw @makeErrorWithCode(67, "Socket already assigned");
app-1      |                                    ^
app-1      | error: Socket already assigned
app-1      |  code: "ERR_HTTP_SOCKET_ASSIGNED"
app-1      | 
app-1      |       at assignSocketInternal (node:http:2058:29)
phoenix-1  | 11:20:09.995 request_id=GDMZlVtWG3pteaUAACkB [info] GET /api/servers/1/statistics/library
phoenix-1  | 11:20:09.995 request_id=GDMZlVtYYlkUvd4AAClB [info] GET /api/servers/1/users/Hutch79
phoenix-1  | 11:20:10.113 request_id=GDMZlVtYYlkUvd4AAClB [info] Sent 200 in 117ms
phoenix-1  | 11:20:10.129 request_id=GDMZlVtWG3pteaUAACkB [info] Sent 200 in 133ms
phoenix-1  | 11:20:10.130 request_id=GDMZlWNdA04Uvd4AACmB [info] GET /api/servers/1/statistics/items
phoenix-1  | 11:20:10.229 request_id=GDMZlWNdA04Uvd4AACmB [info] Sent 200 in 99ms
phoenix-1  | 11:20:11.308 [error] Error syncing items for library Shows: %Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: "2006", message: "null value in column \"name\" of relation \"jellyfin_items\" violates not-null constraint", table: "jellyfin_items", file: "execMain.c", unknown: "ERROR", column: "name", severity: "ERROR", detail: "Failing row contains (34498, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-04 11:20:09, 2025-04-04 11:20:09, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\"{\\\"Url\\\": \\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\"Thumb\": {\"d0c2156a2cdf5dcba92adafc17a88e1e\": \"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).", schema: "public", pg_code: "23502", routine: "ExecConstraints"}, connection_id: 40, query: nil}
phoenix-1  | 11:20:11.308 [warning] Synced 2998 items with 1 errors across all libraries
phoenix-1  | 11:20:11.308 [warning] Errors: ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (34498, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-04 11:20:09, 2025-04-04 11:20:09, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\\\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\\\"Thumb\\\": {\\\"d0c2156a2cdf5dcba92adafc17a88e1e\\\": \\\"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 40, query: nil}"]
phoenix-1  | 11:20:11.308 [info] Sync completed for server My-Media
phoenix-1  | Duration: 144.044 seconds
phoenix-1  | Libraries processed: 2
phoenix-1  | Items processed: 37996
phoenix-1  | API requests: 73
phoenix-1  | Database operations: 35
phoenix-1  | Errors: 2
phoenix-1  | 
phoenix-1  | 11:20:11.309 [info] Items sync completed with result: {:partial, 2998, ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (34498, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-04 11:20:09, 2025-04-04 11:20:09, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\\\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\\\"Thumb\\\": {\\\"d0c2156a2cdf5dcba92adafc17a88e1e\\\": \\\"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 40, query: nil}"]}
phoenix-1  | Items processed: 37996
phoenix-1  | 
phoenix-1  | 11:20:11.309 [info] Starting full activity sync for server My-Media
phoenix-1  | 11:20:11.914 [info] Activity sync completed for server My-Media
phoenix-1  | Duration: 0.605 seconds
phoenix-1  | Activities processed: 4827
app-1      |       at onNodeHTTPRequest (node:http:554:33)
app-1      | 
app-1      | 2053 |   if (self[kCloseCallback])
app-1      | 2054 |     throw new Error("Close callback already set");
app-1      | 2055 |   self[kCloseCallback] = callback;
app-1      | 2056 | }
app-1      | 2057 | function assignSocketInternal(self, socket) {
app-1      | 2058 |     throw @makeErrorWithCode(67, "Socket already assigned");
app-1      |                                    ^
app-1      | error: Socket already assigned
app-1      |  code: "ERR_HTTP_SOCKET_ASSIGNED"
app-1      | 
app-1      |       at assignSocketInternal (node:http:2058:29)
app-1      |       at onNodeHTTPRequest (node:http:554:33)
app-1      | 
app-1      | 2053 |   if (self[kCloseCallback])
app-1      | 2054 |     throw new Error("Close callback already set");
app-1      | 2055 |   self[kCloseCallback] = callback;
app-1      | 2056 | }
app-1      | 2057 | function assignSocketInternal(self, socket) {
app-1      | 2058 |     throw @makeErrorWithCode(67, "Socket already assigned");
app-1      |                                    ^
app-1      | error: Socket already assigned
app-1      |  code: "ERR_HTTP_SOCKET_ASSIGNED"
app-1      | 
app-1      |       at assignSocketInternal (node:http:2058:29)
app-1      |       at onNodeHTTPRequest (node:http:554:33)
app-1      | 
phoenix-1  | Activities inserted: 4827
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
app-1      | 2053 |   if (self[kCloseCallback])
app-1      | 2054 |     throw new Error("Close callback already set");
app-1      | 2055 |   self[kCloseCallback] = callback;
app-1      | 2056 | }
app-1      | 2057 | function assignSocketInternal(self, socket) {
app-1      | 2058 |     throw @makeErrorWithCode(67, "Socket already assigned");
app-1      |                                    ^
app-1      | error: Socket already assigned
app-1      |  code: "ERR_HTTP_SOCKET_ASSIGNED"
app-1      | 
app-1      |       at assignSocketInternal (node:http:2058:29)
app-1      |       at onNodeHTTPRequest (node:http:554:33)
app-1      | 
app-1      | 2053 |   if (self[kCloseCallback])
app-1      | 2054 |     throw new Error("Close callback already set");
phoenix-1  | API requests: 2
phoenix-1  | Database operations: 1
phoenix-1  | Errors: 0
phoenix-1  | 
phoenix-1  | 11:20:11.914 [info] Successfully synced 4827 activities for server My-Media
phoenix-1  | 11:20:11.914 [info] Activities sync completed with result: {:ok, 4827}
phoenix-1  | Activities processed: 4827
phoenix-1  | 
phoenix-1  | 11:20:11.914 [error] Error during full_sync for server My-Media: %CaseClauseError{term: {:partial, :some_operations_partial}}
```

**Comment by fredrikburmester** [comment]
Please update to latest `:edge` and see if this is resolved!

**Comment by Hutch79** [comment]
Just updated to latest edge, but still not syncing correctly.

```
streamystats-phoenix-1  | 21:07:15.649 [error] Error syncing items for library Shows: %Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: "2006", message: "null value in column \"name\" of relation \"jellyfin_items\" violates not-null constraint", table: "jellyfin_items", file: "execMain.c", unknown: "ERROR", column: "name", severity: "ERROR", detail: "Failing row contains (124977, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-05 21:07:13, 2025-04-05 21:07:13, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\"{\\\"Url\\\": \\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\"Thumb\": {\"d0c2156a2cdf5dcba92adafc17a88e1e\": \"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).", schema: "public", pg_code: "23502", routine: "ExecConstraints"}, connection_id: 45, query: nil}
streamystats-phoenix-1  | 21:07:15.649 [warning] Synced 2998 items with 1 errors across all libraries
streamystats-phoenix-1  | 21:07:15.649 [warning] Errors: ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (124977, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-05 21:07:13, 2025-04-05 21:07:13, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\\\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\\\"Thumb\\\": {\\\"d0c2156a2cdf5dcba92adafc17a88e1e\\\": \\\"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 45, query: nil}"]
streamystats-phoenix-1  | 21:07:15.649 [info] Sync completed for server Luwu-Media
streamystats-phoenix-1  | Duration: 104.655 seconds
streamystats-phoenix-1  | Libraries processed: 2
streamystats-phoenix-1  | Items processed: 37996
streamystats-phoenix-1  | API requests: 73
streamystats-phoenix-1  | Database operations: 35
streamystats-phoenix-1  | Errors: 2
```

**Comment by fredrikburmester** [comment]
- The watch stats won't show until you watch content. I can't calculate watch time from before you installed Streamystats. 
- It looks like you have just a few errors with items missing a name, which is a required column. It's nothing to worry about. 
- The sharp issues in the frontend code is fixed.

**Comment by Hutch79** [comment]
> The watch stats won't show until you watch content. I can't calculate watch time from before you installed Streamystats.

Good to know, I suspected that.

> It looks like you have just a few errors with items missing a name, which is a required column. It's nothing to worry about.

I suspect the scan exiting when encountering such an item.
Otherwise, I have over 10k items without a name.

**Comment by fredrikburmester** [comment]
Ah, I see. I've pushed a change https://github.com/fredrikburmester/streamystats/commit/01729b44f1fe953aaa0ac37160dc2dd0c4d0047b to always set a name, please update and try again. Thanks.

**Comment by Hutch79** [comment]
Hey, unfortunately it failed again:
```
streamystats-phoenix-1  | 13:40:38.928 [error] Error syncing items for library Shows: %Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: "2006", message: "null value in column \"name\" of relation \"jellyfin_items\" violates not-null constraint", table: "jellyfin_items", file: "execMain.c", unknown: "ERROR", column: "name", severity: "ERROR", detail: "Failing row contains (350342, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-07 13:40:37, 2025-04-07 13:40:37, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\"{\\\"Url\\\": \\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\"Thumb\": {\"d0c2156a2cdf5dcba92adafc17a88e1e\": \"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).", schema: "public", pg_code: "23502", routine: "ExecConstraints"}, connection_id: 335, query: nil}
streamystats-phoenix-1  | 13:40:38.929 [warning] Synced 2999 items with 1 errors across all libraries
streamystats-phoenix-1  | 13:40:38.929 [warning] Errors: ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (350342, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-07 13:40:37, 2025-04-07 13:40:37, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\\\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\\\"Thumb\\\": {\\\"d0c2156a2cdf5dcba92adafc17a88e1e\\\": \\\"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 335, query: nil}"]
streamystats-phoenix-1  | 13:40:38.929 [info] Sync completed for server My-Media
streamystats-phoenix-1  | Duration: 104.175 seconds
streamystats-phoenix-1  | Libraries processed: 2
streamystats-phoenix-1  | Items processed: 37998
streamystats-phoenix-1  | API requests: 73
streamystats-phoenix-1  | Database operations: 35
streamystats-phoenix-1  | Errors: 2
streamystats-phoenix-1  | 
streamystats-phoenix-1  | 13:40:38.929 [info] Items sync completed with result: {:partial, 2999, ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (350342, 0bc5c6200a8dd6e247998fb891a9493a, null, Episode, 2, 1, 2025-04-07 13:40:37, 2025-04-07 13:40:37, null, 95cb48009eab3d058d1dded83f7b9d73, 2024-12-28 16:14:17, null, 000 - 0004 - , 2020-02-13 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10258043\\\\\\\"..., null, null, null, {}, null, null, 2020, f, af2f36859a0e206830bf8c72097c985d, Video, null, null, Ragnarok, b74d2428681bc1378c116843c01aa26d, af2f36859a0e206830bf8c72097c985d, Specials, 4, null, {}, {\\\"Thumb\\\": {\\\"d0c2156a2cdf5dcba92adafc17a88e1e\\\": \\\"NyC*hKtRaztRWBWY..., 0, VideoFile, null, null, b74d2428681bc1378c116843c01aa26d, {cc0ebde341259203da5bf87cd66c8cf1,058daff1517b62546e09f8da371d74..., b74d2428681bc1378c116843c01aa26d, d0c2156a2cdf5dcba92adafc17a88e1e, Virtual, 0.68, 058daff1517b62546e09f8da371d741e, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 335, query: nil}"]}
streamystats-phoenix-1  | Items processed: 37998
streamystats-phoenix-1  | 
streamystats-phoenix-1  | 13:40:38.929 [info] Starting full activity sync for server My-Media
streamystats-phoenix-1  | 13:40:39.270 [info] Activity sync completed for server My-Media
streamystats-phoenix-1  | Duration: 0.341 seconds
streamystats-phoenix-1  | Activities processed: 4407
streamystats-phoenix-1  | Activities inserted: 0
streamystats-phoenix-1  | API requests: 2
streamystats-phoenix-1  | Database operations: 1
streamystats-phoenix-1  | Errors: 0
streamystats-phoenix-1  | 
streamystats-phoenix-1  | 13:40:39.270 [info] Successfully synced 0 activities for server My-Media
streamystats-phoenix-1  | 13:40:39.270 [info] Activities sync completed with result: {:ok, 0}
streamystats-phoenix-1  | Activities processed: 4407
streamystats-phoenix-1  | 
streamystats-phoenix-1  | 13:40:39.270 [error] Error during full_sync for server My-Media: %CaseClauseError{term: {:partial, :some_operations_partial}}
```

It claims to have processed 37'998 Items, which is 5k items short of what Infuse claims to have in its library.
But even if this number is correct, it only shows me a total of 31'687 items (Movies + Episodes) on the Library page.

**Comment by Hutch79** [comment]
I think i found the issue.
You'll see a tvdb in the error:
https://www.thetvdb.com/series/ragnarok/episodes/10258043
If I remove theTvDb from the series, the scan is successful.

**Comment by Hutch79** [comment]
After removing the TvDb ID from 3 series, the error I'm getting is a timeout error.
Therefore, I still have not all my Series scanned correctly.
Also, could you please reopen the Issue since this is not resolved?
```
streamystats-phoenix-1  | 08:06:55.808 [error] Error fetching items: "HTTP request failed: timeout"
streamystats-phoenix-1  | 08:06:55.897 [info] Synced 13500 items for library Shows
streamystats-phoenix-1  | 08:06:55.897 [info] Synced 16499 items across all libraries
streamystats-phoenix-1  | 08:06:55.898 [info] Sync completed for server Luwu-Media
streamystats-phoenix-1  | Duration: 53.827 seconds
streamystats-phoenix-1  | Libraries processed: 2
streamystats-phoenix-1  | Items processed: 32998
streamystats-phoenix-1  | API requests: 37
streamystats-phoenix-1  | Database operations: 17
streamystats-phoenix-1  | Errors: 1
```

**Comment by Hutch79** [comment]
I've just cleaned up my Jellyfin install.
I uninstalled all third party (not preinstalled) metadata plugins, deleted the metadata folder and did a complete rescan/replace of all metadata. After that, the scan was successful.

From my side, this issue is resolved, although I think some better error handling would be beneficial.

**Comment by fredrikburmester** [comment]
Thank you, I'll try to improve error handling. Happy that it's working for you.

**Comment by Hutch79** [comment]
Oh, btw. if you want to test any further improvements, I'll keep the "old" install for testing.
Just let me know if there is anything new!

**Comment by fredrikburmester** [comment]
I've pushed an update https://github.com/fredrikburmester/streamystats/commit/dc2a8e3c0fa544acf10a227dc2e88cbc4f318c2f that hopefully will fix the null item name issue. I don't really understand why removing the tvdb stuff would help, but if you can please try it again!

**Comment by Hutch79** [comment]
I don't know if I find time today.

In the metadata editor, I saw lots of non-existent episodes in my seasons, but only while having tvdb active.
When removing the plugin and rescanning (replace all metadata), they are gone.

**Comment by Hutch79** [comment]
Unfortunately, the error still occurs.
Here's the Log:

```
streamystats-test-phoenix-1  | 14:22:43.539 request_id=GDbSgn0bCoDIePUAAFXB [info] GET /api/admin/servers/1/sync/tasks
streamystats-test-phoenix-1  | 14:22:43.543 request_id=GDbSgn0bCoDIePUAAFXB [info] Sent 200 in 4ms
streamystats-test-phoenix-1  | 14:24:08.172 [error] Error syncing items for library Shows: %Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: "2006", message: "null value in column \"name\" of relation \"jellyfin_items\" violates not-null constraint", table: "jellyfin_items", file: "execMain.c", unknown: "ERROR", column: "name", severity: "ERROR", detail: "Failing row contains (114756, d517c9cfb5c1955cecb7c62fb99c0961, null, Episode, 2, 1, 2025-04-16 14:24:08, 2025-04-16 14:24:08, null, 37802eed1c5cd3d11c2daea625f58eee, 2024-12-28 16:14:17, null, 000 - 0005 - , 2021-12-24 00:00:00, {\"{\\\"Url\\\": \\\"https://www.thetvdb.com/?tab=episode&id=10159957\\\"..., null, TV-14, null, {}, null, null, 2021, f, d2b9b13aeae26f22cbaf86c7cb75688a, Video, null, null, Jujutsu Kaisen, 4895b87cccd8daf1f52f96cd50f92e26, d2b9b13aeae26f22cbaf86c7cb75688a, Specials, 5, null, {}, {\"Thumb\": {\"dfbc0693e5dd1d86a211c9607b2447cd\": \"NH8}Q4XmN#aJD~-W..., 0, VideoFile, null, null, 4895b87cccd8daf1f52f96cd50f92e26, {ad9f80ea8aa9b88a7c915dda3cb00db8,6e97ea47b796507525e88fc40e077a..., 4895b87cccd8daf1f52f96cd50f92e26, dfbc0693e5dd1d86a211c9607b2447cd, Virtual, 0.68, 6e97ea47b796507525e88fc40e077a63, null, null).", schema: "public", pg_code: "23502", routine: "ExecConstraints"}, connection_id: 156, query: nil}
streamystats-test-phoenix-1  | 14:24:08.172 [warning] Synced 3070 items with 1 errors across all libraries
streamystats-test-phoenix-1  | 14:24:08.172 [warning] Errors: ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (114756, d517c9cfb5c1955cecb7c62fb99c0961, null, Episode, 2, 1, 2025-04-16 14:24:08, 2025-04-16 14:24:08, null, 37802eed1c5cd3d11c2daea625f58eee, 2024-12-28 16:14:17, null, 000 - 0005 - , 2021-12-24 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10159957\\\\\\\"..., null, TV-14, null, {}, null, null, 2021, f, d2b9b13aeae26f22cbaf86c7cb75688a, Video, null, null, Jujutsu Kaisen, 4895b87cccd8daf1f52f96cd50f92e26, d2b9b13aeae26f22cbaf86c7cb75688a, Specials, 5, null, {}, {\\\"Thumb\\\": {\\\"dfbc0693e5dd1d86a211c9607b2447cd\\\": \\\"NH8}Q4XmN#aJD~-W..., 0, VideoFile, null, null, 4895b87cccd8daf1f52f96cd50f92e26, {ad9f80ea8aa9b88a7c915dda3cb00db8,6e97ea47b796507525e88fc40e077a..., 4895b87cccd8daf1f52f96cd50f92e26, dfbc0693e5dd1d86a211c9607b2447cd, Virtual, 0.68, 6e97ea47b796507525e88fc40e077a63, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 156, query: nil}"]
streamystats-test-phoenix-1  | 14:24:08.172 [info] Sync completed for server My-Media
streamystats-test-phoenix-1  | Duration: 101.755 seconds
streamystats-test-phoenix-1  | Libraries processed: 2
streamystats-test-phoenix-1  | Items processed: 32140
streamystats-test-phoenix-1  | API requests: 62
streamystats-test-phoenix-1  | Database operations: 30
streamystats-test-phoenix-1  | Errors: 2
streamystats-test-phoenix-1  | 
streamystats-test-phoenix-1  | 14:24:08.172 [info] Items sync completed with result: {:partial, 3070, ["%Postgrex.Error{message: nil, postgres: %{code: :not_null_violation, line: \"2006\", message: \"null value in column \\\"name\\\" of relation \\\"jellyfin_items\\\" violates not-null constraint\", table: \"jellyfin_items\", file: \"execMain.c\", unknown: \"ERROR\", column: \"name\", severity: \"ERROR\", detail: \"Failing row contains (114756, d517c9cfb5c1955cecb7c62fb99c0961, null, Episode, 2, 1, 2025-04-16 14:24:08, 2025-04-16 14:24:08, null, 37802eed1c5cd3d11c2daea625f58eee, 2024-12-28 16:14:17, null, 000 - 0005 - , 2021-12-24 00:00:00, {\\\"{\\\\\\\"Url\\\\\\\": \\\\\\\"https://www.thetvdb.com/?tab=episode&id=10159957\\\\\\\"..., null, TV-14, null, {}, null, null, 2021, f, d2b9b13aeae26f22cbaf86c7cb75688a, Video, null, null, Jujutsu Kaisen, 4895b87cccd8daf1f52f96cd50f92e26, d2b9b13aeae26f22cbaf86c7cb75688a, Specials, 5, null, {}, {\\\"Thumb\\\": {\\\"dfbc0693e5dd1d86a211c9607b2447cd\\\": \\\"NH8}Q4XmN#aJD~-W..., 0, VideoFile, null, null, 4895b87cccd8daf1f52f96cd50f92e26, {ad9f80ea8aa9b88a7c915dda3cb00db8,6e97ea47b796507525e88fc40e077a..., 4895b87cccd8daf1f52f96cd50f92e26, dfbc0693e5dd1d86a211c9607b2447cd, Virtual, 0.68, 6e97ea47b796507525e88fc40e077a63, null, null).\", schema: \"public\", pg_code: \"23502\", routine: \"ExecConstraints\"}, connection_id: 156, query: nil}"]}
streamystats-test-phoenix-1  | Items processed: 32140
streamystats-test-phoenix-1  | 
streamystats-test-phoenix-1  | 14:24:08.172 [info] Starting full activity sync for server My-Media
streamystats-test-phoenix-1  | 14:24:08.448 [info] Activity sync completed for server My-Media
streamystats-test-phoenix-1  | Duration: 0.276 seconds
streamystats-test-phoenix-1  | Activities processed: 3446
streamystats-test-phoenix-1  | Activities inserted: 0
streamystats-test-phoenix-1  | API requests: 2
streamystats-test-phoenix-1  | Database operations: 1
streamystats-test-phoenix-1  | Errors: 0
streamystats-test-phoenix-1  | 
streamystats-test-phoenix-1  | 14:24:08.448 [info] Successfully synced 0 activities for server My-Media
streamystats-test-phoenix-1  | 14:24:08.448 [info] Activities sync completed with result: {:ok, 0}
streamystats-test-phoenix-1  | Activities processed: 3446
streamystats-test-phoenix-1  | 
streamystats-test-phoenix-1  | 14:24:08.449 [error] Error during full_sync for server My-Media: %CaseClauseError{term: {:partial, :some_operations_partial}}
```

**Comment by fredrikburmester** [comment]
I've made more improvements. Please try again.

**Comment by Hutch79** [comment]
Is this on edge or on a specific tag?

**Comment by fredrikburmester** [comment]
Edge

**Comment by fredrikburmester** [comment]
Hello, please test this again if possible. Otherwise I'll close this until the issue shows up again.

**Comment by Hutch79** [comment]
Heya, sorry for the late response.
I migrated my server two weeks ago and forgot to migrate my old media server for continued testing.

My best guess would be that the issue was caused by a combination of continues upgrading of Jellyfin as well as Plugin install/uninstalls which lead to database and/or metadata corruption.
Therefore, I agree with you and will close this ticket until this error occurs again.
